FROM python:3.9-slim

WORKDIR /app

# Copy requirements
COPY kafka/requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy Kafka producer code
COPY kafka/ .

# Run producer
CMD ["python", "producer.py"]
